export { useSpendingBreakdown } from './hooks/useSpendingBreakdown'
export { useTimePeriod } from './hooks/useTimePeriod'
export { useSpendingComparison } from './hooks/useSpendingComparison'
export { CategoryBreakdown } from './components/CategoryBreakdown'
export { SpendingSummary } from './components/SpendingSummary'
export { ComparisonIndicator } from './components/ComparisonIndicator'
export { TimePeriodSelector } from './components/TimePeriodSelector'
export { DashboardPage } from './components/DashboardPage'
export { resolveTimePeriod, getTimePeriodLabel } from './utils/resolveTimePeriod'
export { getPreviousPeriodRange, computeComparison, getComparisonLabel } from './utils/computeComparison'
export type { TimePeriod, TimePeriodPreset, TimePeriodCustom, ResolvedDateRange } from './types'
export type { ComparisonResult } from './utils/computeComparison'
export type { SpendingComparison } from './hooks/useSpendingComparison'
