/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuersIndexRouteImport } from './routes/issuers.index'
import { Route as IssuersIssuerIdRouteImport } from './routes/issuers.$issuerId'
import { Route as IssuersIssuerIdIndexRouteImport } from './routes/issuers.$issuerId.index'
import { Route as IssuersIssuerIdRulesNewRouteImport } from './routes/issuers.$issuerId.rules.new'
import { Route as IssuersIssuerIdRulesRuleIdRouteImport } from './routes/issuers.$issuerId.rules.$ruleId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIndexRoute = IssuersIndexRouteImport.update({
  id: '/issuers/',
  path: '/issuers/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIssuerIdRoute = IssuersIssuerIdRouteImport.update({
  id: '/issuers/$issuerId',
  path: '/issuers/$issuerId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIssuerIdIndexRoute = IssuersIssuerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IssuersIssuerIdRoute,
} as any)
const IssuersIssuerIdRulesNewRoute = IssuersIssuerIdRulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => IssuersIssuerIdRoute,
} as any)
const IssuersIssuerIdRulesRuleIdRoute =
  IssuersIssuerIdRulesRuleIdRouteImport.update({
    id: '/rules/$ruleId',
    path: '/rules/$ruleId',
    getParentRoute: () => IssuersIssuerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/issuers/$issuerId': typeof IssuersIssuerIdRouteWithChildren
  '/issuers/': typeof IssuersIndexRoute
  '/issuers/$issuerId/': typeof IssuersIssuerIdIndexRoute
  '/issuers/$issuerId/rules/$ruleId': typeof IssuersIssuerIdRulesRuleIdRoute
  '/issuers/$issuerId/rules/new': typeof IssuersIssuerIdRulesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/issuers': typeof IssuersIndexRoute
  '/issuers/$issuerId': typeof IssuersIssuerIdIndexRoute
  '/issuers/$issuerId/rules/$ruleId': typeof IssuersIssuerIdRulesRuleIdRoute
  '/issuers/$issuerId/rules/new': typeof IssuersIssuerIdRulesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/issuers/$issuerId': typeof IssuersIssuerIdRouteWithChildren
  '/issuers/': typeof IssuersIndexRoute
  '/issuers/$issuerId/': typeof IssuersIssuerIdIndexRoute
  '/issuers/$issuerId/rules/$ruleId': typeof IssuersIssuerIdRulesRuleIdRoute
  '/issuers/$issuerId/rules/new': typeof IssuersIssuerIdRulesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/import'
    | '/transactions'
    | '/issuers/$issuerId'
    | '/issuers/'
    | '/issuers/$issuerId/'
    | '/issuers/$issuerId/rules/$ruleId'
    | '/issuers/$issuerId/rules/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/import'
    | '/transactions'
    | '/issuers'
    | '/issuers/$issuerId'
    | '/issuers/$issuerId/rules/$ruleId'
    | '/issuers/$issuerId/rules/new'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/import'
    | '/transactions'
    | '/issuers/$issuerId'
    | '/issuers/'
    | '/issuers/$issuerId/'
    | '/issuers/$issuerId/rules/$ruleId'
    | '/issuers/$issuerId/rules/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ImportRoute: typeof ImportRoute
  TransactionsRoute: typeof TransactionsRoute
  IssuersIssuerIdRoute: typeof IssuersIssuerIdRouteWithChildren
  IssuersIndexRoute: typeof IssuersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/': {
      id: '/issuers/'
      path: '/issuers'
      fullPath: '/issuers/'
      preLoaderRoute: typeof IssuersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/$issuerId': {
      id: '/issuers/$issuerId'
      path: '/issuers/$issuerId'
      fullPath: '/issuers/$issuerId'
      preLoaderRoute: typeof IssuersIssuerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/$issuerId/': {
      id: '/issuers/$issuerId/'
      path: '/'
      fullPath: '/issuers/$issuerId/'
      preLoaderRoute: typeof IssuersIssuerIdIndexRouteImport
      parentRoute: typeof IssuersIssuerIdRoute
    }
    '/issuers/$issuerId/rules/new': {
      id: '/issuers/$issuerId/rules/new'
      path: '/rules/new'
      fullPath: '/issuers/$issuerId/rules/new'
      preLoaderRoute: typeof IssuersIssuerIdRulesNewRouteImport
      parentRoute: typeof IssuersIssuerIdRoute
    }
    '/issuers/$issuerId/rules/$ruleId': {
      id: '/issuers/$issuerId/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/issuers/$issuerId/rules/$ruleId'
      preLoaderRoute: typeof IssuersIssuerIdRulesRuleIdRouteImport
      parentRoute: typeof IssuersIssuerIdRoute
    }
  }
}

interface IssuersIssuerIdRouteChildren {
  IssuersIssuerIdIndexRoute: typeof IssuersIssuerIdIndexRoute
  IssuersIssuerIdRulesRuleIdRoute: typeof IssuersIssuerIdRulesRuleIdRoute
  IssuersIssuerIdRulesNewRoute: typeof IssuersIssuerIdRulesNewRoute
}

const IssuersIssuerIdRouteChildren: IssuersIssuerIdRouteChildren = {
  IssuersIssuerIdIndexRoute: IssuersIssuerIdIndexRoute,
  IssuersIssuerIdRulesRuleIdRoute: IssuersIssuerIdRulesRuleIdRoute,
  IssuersIssuerIdRulesNewRoute: IssuersIssuerIdRulesNewRoute,
}

const IssuersIssuerIdRouteWithChildren = IssuersIssuerIdRoute._addFileChildren(
  IssuersIssuerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ImportRoute: ImportRoute,
  TransactionsRoute: TransactionsRoute,
  IssuersIssuerIdRoute: IssuersIssuerIdRouteWithChildren,
  IssuersIndexRoute: IssuersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
