/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IssuersIndexRouteImport } from './routes/issuers.index'
import { Route as IssuersIssuerIdRouteImport } from './routes/issuers.$issuerId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIndexRoute = IssuersIndexRouteImport.update({
  id: '/issuers/',
  path: '/issuers/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuersIssuerIdRoute = IssuersIssuerIdRouteImport.update({
  id: '/issuers/$issuerId',
  path: '/issuers/$issuerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/issuers/$issuerId': typeof IssuersIssuerIdRoute
  '/issuers/': typeof IssuersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/issuers/$issuerId': typeof IssuersIssuerIdRoute
  '/issuers': typeof IssuersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/import': typeof ImportRoute
  '/transactions': typeof TransactionsRoute
  '/issuers/$issuerId': typeof IssuersIssuerIdRoute
  '/issuers/': typeof IssuersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/import'
    | '/transactions'
    | '/issuers/$issuerId'
    | '/issuers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/import'
    | '/transactions'
    | '/issuers/$issuerId'
    | '/issuers'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/import'
    | '/transactions'
    | '/issuers/$issuerId'
    | '/issuers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  ImportRoute: typeof ImportRoute
  TransactionsRoute: typeof TransactionsRoute
  IssuersIssuerIdRoute: typeof IssuersIssuerIdRoute
  IssuersIndexRoute: typeof IssuersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/': {
      id: '/issuers/'
      path: '/issuers'
      fullPath: '/issuers/'
      preLoaderRoute: typeof IssuersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issuers/$issuerId': {
      id: '/issuers/$issuerId'
      path: '/issuers/$issuerId'
      fullPath: '/issuers/$issuerId'
      preLoaderRoute: typeof IssuersIssuerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  ImportRoute: ImportRoute,
  TransactionsRoute: TransactionsRoute,
  IssuersIssuerIdRoute: IssuersIssuerIdRoute,
  IssuersIndexRoute: IssuersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
